name: harmful-content-detection

services:
  - name: api
    source_dir: apps/api
    dockerfile_path: apps/api/Dockerfile
    run_command: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    http_port: 8080

workers:
  - name: worker
    source_dir: apps/api
    dockerfile_path: apps/api/Dockerfile
    run_command: celery -A app.workers.celery_app.celery_app worker --loglevel=info
