name: harmful-content-detection

services:
  - name: api
    dockerfile_path: apps/api/Dockerfile
    source_dir: /
    run_command: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    http_port: 8080

    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
      - key: REDIS_URL
        scope: RUN_TIME
      - key: JWT_SECRET
        scope: RUN_TIME
      - key: JWT_ALGORITHM
        value: HS256
        scope: RUN_TIME
      - key: JWT_EXPIRE_MINUTES
        value: "120"
        scope: RUN_TIME
      - key: DEMO_MODE
        value: "false"
        scope: RUN_TIME
      - key: NLP_ADAPTER_PATH
        value: /app/app/hf_infer.py
        scope: RUN_TIME
      - key: HF_MODEL_URL
        scope: RUN_TIME
      - key: HF_API_TOKEN
        scope: RUN_TIME
      - key: HF_TIMEOUT_SEC
        value: "30"
        scope: RUN_TIME
      - key: CORS_ORIGINS
        scope: RUN_TIME

workers:
  - name: worker
    dockerfile_path: apps/api/Dockerfile
    source_dir: /
    run_command: celery -A app.workers.celery_app.celery_app worker --loglevel=info

    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
      - key: REDIS_URL
        scope: RUN_TIME
      - key: JWT_SECRET
        scope: RUN_TIME